// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/kong/terraform-provider-konnect/internal/sdk"
	"github.com/kong/terraform-provider-konnect/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect/internal/sdk/models/shared"
	"github.com/kong/terraform-provider-konnect/internal/validators"
	"math/big"
	"time"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &APIProductResource{}
var _ resource.ResourceWithImportState = &APIProductResource{}

func NewAPIProductResource() resource.Resource {
	return &APIProductResource{}
}

// APIProductResource defines the resource implementation.
type APIProductResource struct {
	client *sdk.Konnect
}

// APIProductResourceModel describes the resource data model.
type APIProductResourceModel struct {
	CreatedAt    types.String            `tfsdk:"created_at"`
	Description  types.String            `tfsdk:"description"`
	ID           types.String            `tfsdk:"id"`
	Labels       map[string]types.String `tfsdk:"labels"`
	Name         types.String            `tfsdk:"name"`
	PortalIds    []types.String          `tfsdk:"portal_ids"`
	UpdatedAt    types.String            `tfsdk:"updated_at"`
	VersionCount types.Number            `tfsdk:"version_count"`
}

func (r *APIProductResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_api_product"
}

func (r *APIProductResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "APIProduct Resource",

		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `An ISO-8601 timestamp representation of entity creation date.`,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The description of the API product. Default: null`,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `API product identifier`,
			},
			"labels": schema.MapAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				MarkdownDescription: `description: A maximum of 5 user-defined labels are allowed on this resource.` + "\n" +
					`Keys must not start with kong, konnect, insomnia, mesh, kic or _, which are reserved for Kong.` + "\n" +
					`Keys are case-sensitive.` + "\n" +
					``,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: `The name of the API product.`,
			},
			"portal_ids": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				Description: `The list of portal identifiers which this API product should be published to`,
				Validators: []validator.List{
					listvalidator.UniqueValues(),
				},
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `An ISO-8601 timestamp representation of entity update date.`,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
			},
			"version_count": schema.NumberAttribute{
				Computed:    true,
				Description: `The number of product versions attached to this API product`,
			},
		},
	}
}

func (r *APIProductResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Konnect)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.Konnect, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *APIProductResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *APIProductResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	description := new(string)
	if !data.Description.IsUnknown() && !data.Description.IsNull() {
		*description = data.Description.ValueString()
	} else {
		description = nil
	}
	labels := make(map[string]string)
	for labelsKey, labelsValue := range data.Labels {
		labelsInst := labelsValue.ValueString()
		labels[labelsKey] = labelsInst
	}
	var portalIds []string = nil
	for _, portalIdsItem := range data.PortalIds {
		portalIds = append(portalIds, portalIdsItem.ValueString())
	}
	request := shared.CreateAPIProductDTO{
		Name:        name,
		Description: description,
		Labels:      labels,
		PortalIds:   portalIds,
	}
	res, err := r.client.APIProducts.CreateAPIProduct(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 201 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.APIProduct == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	if res.APIProduct != nil {
		data.CreatedAt = types.StringValue(res.APIProduct.CreatedAt.Format(time.RFC3339Nano))
		data.Description = types.StringPointerValue(res.APIProduct.Description)
		data.ID = types.StringValue(res.APIProduct.ID)
		if len(res.APIProduct.Labels) > 0 {
			data.Labels = make(map[string]types.String)
			for key, value := range res.APIProduct.Labels {
				data.Labels[key] = types.StringValue(value)
			}
		}
		data.Name = types.StringValue(res.APIProduct.Name)
		data.PortalIds = []types.String{}
		for _, v := range res.APIProduct.PortalIds {
			data.PortalIds = append(data.PortalIds, types.StringValue(v))
		}
		data.UpdatedAt = types.StringValue(res.APIProduct.UpdatedAt.Format(time.RFC3339Nano))
		data.VersionCount = types.NumberValue(big.NewFloat(float64(res.APIProduct.VersionCount)))
	}
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *APIProductResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *APIProductResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetAPIProductRequest{
		ID: id,
	}
	res, err := r.client.APIProducts.GetAPIProduct(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.APIProduct == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	if res.APIProduct != nil {
		data.CreatedAt = types.StringValue(res.APIProduct.CreatedAt.Format(time.RFC3339Nano))
		data.Description = types.StringPointerValue(res.APIProduct.Description)
		data.ID = types.StringValue(res.APIProduct.ID)
		if len(res.APIProduct.Labels) > 0 {
			data.Labels = make(map[string]types.String)
			for key, value := range res.APIProduct.Labels {
				data.Labels[key] = types.StringValue(value)
			}
		}
		data.Name = types.StringValue(res.APIProduct.Name)
		data.PortalIds = []types.String{}
		for _, v := range res.APIProduct.PortalIds {
			data.PortalIds = append(data.PortalIds, types.StringValue(v))
		}
		data.UpdatedAt = types.StringValue(res.APIProduct.UpdatedAt.Format(time.RFC3339Nano))
		data.VersionCount = types.NumberValue(big.NewFloat(float64(res.APIProduct.VersionCount)))
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *APIProductResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *APIProductResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	name := new(string)
	if !data.Name.IsUnknown() && !data.Name.IsNull() {
		*name = data.Name.ValueString()
	} else {
		name = nil
	}
	description := new(string)
	if !data.Description.IsUnknown() && !data.Description.IsNull() {
		*description = data.Description.ValueString()
	} else {
		description = nil
	}
	labels := make(map[string]string)
	for labelsKey, labelsValue := range data.Labels {
		labelsInst := labelsValue.ValueString()
		labels[labelsKey] = labelsInst
	}
	var portalIds []string = nil
	for _, portalIdsItem := range data.PortalIds {
		portalIds = append(portalIds, portalIdsItem.ValueString())
	}
	updateAPIProductDTO := shared.UpdateAPIProductDTO{
		Name:        name,
		Description: description,
		Labels:      labels,
		PortalIds:   portalIds,
	}
	request := operations.UpdateAPIProductRequest{
		ID:                  id,
		UpdateAPIProductDTO: updateAPIProductDTO,
	}
	res, err := r.client.APIProducts.UpdateAPIProduct(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.APIProduct == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	if res.APIProduct != nil {
		data.CreatedAt = types.StringValue(res.APIProduct.CreatedAt.Format(time.RFC3339Nano))
		data.Description = types.StringPointerValue(res.APIProduct.Description)
		data.ID = types.StringValue(res.APIProduct.ID)
		if len(res.APIProduct.Labels) > 0 {
			data.Labels = make(map[string]types.String)
			for key, value := range res.APIProduct.Labels {
				data.Labels[key] = types.StringValue(value)
			}
		}
		data.Name = types.StringValue(res.APIProduct.Name)
		data.PortalIds = []types.String{}
		for _, v := range res.APIProduct.PortalIds {
			data.PortalIds = append(data.PortalIds, types.StringValue(v))
		}
		data.UpdatedAt = types.StringValue(res.APIProduct.UpdatedAt.Format(time.RFC3339Nano))
		data.VersionCount = types.NumberValue(big.NewFloat(float64(res.APIProduct.VersionCount)))
	}
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *APIProductResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *APIProductResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.DeleteAPIProductRequest{
		ID: id,
	}
	res, err := r.client.APIProducts.DeleteAPIProduct(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 204 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *APIProductResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
