name: Publish

on:
  push:
    paths:
      - ".speakeasy/gen.lock"
    branches:
      - main

jobs:
  publish-terraform:
    name: Publish Terraform Provider
    runs-on: ubuntu-latest
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.TERRAFORM_GPG_PRIVATE_KEY }}
      - id: release
        uses: speakeasy-api/sdk-generation-action@v14
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          gpg_fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}
          action: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
